# Generated by Django 3.0.7 on 2020-06-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktheme',
            name='book_code',
        ),
        migrations.AddField(
            model_name='book',
            name='theme_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.BookTheme'),
        ),
    ]
