# Generated by Django 3.0.7 on 2020-06-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200607_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Автор',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='год издания',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='цена',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Издательство',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Название',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='bookordered',
            old_name='Книга',
            new_name='book_code',
        ),
        migrations.RenameField(
            model_name='bookordered',
            old_name='Заказ',
            new_name='order_code',
        ),
        migrations.RenameField(
            model_name='bookordered',
            old_name='Отметка о возврате',
            new_name='return_mark',
        ),
        migrations.RenameField(
            model_name='booktheme',
            old_name='Жанр',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Дата заказа',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Читатель',
            new_name='reader_code',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Имя',
            new_name='fathername',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Отчество',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Телефон',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Фамилия',
            new_name='surname',
        ),
    ]
